//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 10:50:17 PM GMT 
//


package com.emiage2018s1.notes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.emiage2018s1.notes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.emiage2018s1.notes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllNoteDetailsRequest }
     * 
     */
    public GetAllNoteDetailsRequest createGetAllNoteDetailsRequest() {
        return new GetAllNoteDetailsRequest();
    }

    /**
     * Create an instance of {@link AddUserDetailsResponse }
     * 
     */
    public AddUserDetailsResponse createAddUserDetailsResponse() {
        return new AddUserDetailsResponse();
    }

    /**
     * Create an instance of {@link EditNoteDetailsResponse }
     * 
     */
    public EditNoteDetailsResponse createEditNoteDetailsResponse() {
        return new EditNoteDetailsResponse();
    }

    /**
     * Create an instance of {@link NoteDetails }
     * 
     */
    public NoteDetails createNoteDetails() {
        return new NoteDetails();
    }

    /**
     * Create an instance of {@link AddNoteDetailsRequest }
     * 
     */
    public AddNoteDetailsRequest createAddNoteDetailsRequest() {
        return new AddNoteDetailsRequest();
    }

    /**
     * Create an instance of {@link AddNoteDetails }
     * 
     */
    public AddNoteDetails createAddNoteDetails() {
        return new AddNoteDetails();
    }

    /**
     * Create an instance of {@link DeleteNoteDetailsResponse }
     * 
     */
    public DeleteNoteDetailsResponse createDeleteNoteDetailsResponse() {
        return new DeleteNoteDetailsResponse();
    }

    /**
     * Create an instance of {@link AddUserDetailsRequest }
     * 
     */
    public AddUserDetailsRequest createAddUserDetailsRequest() {
        return new AddUserDetailsRequest();
    }

    /**
     * Create an instance of {@link UserDetails }
     * 
     */
    public UserDetails createUserDetails() {
        return new UserDetails();
    }

    /**
     * Create an instance of {@link ConnxionRequest }
     * 
     */
    public ConnxionRequest createConnxionRequest() {
        return new ConnxionRequest();
    }

    /**
     * Create an instance of {@link ConnexionResponse }
     * 
     */
    public ConnexionResponse createConnexionResponse() {
        return new ConnexionResponse();
    }

    /**
     * Create an instance of {@link DeleteNoteDetailsRequest }
     * 
     */
    public DeleteNoteDetailsRequest createDeleteNoteDetailsRequest() {
        return new DeleteNoteDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllNoteDetailsResponse }
     * 
     */
    public GetAllNoteDetailsResponse createGetAllNoteDetailsResponse() {
        return new GetAllNoteDetailsResponse();
    }

    /**
     * Create an instance of {@link GetNoteDetailsRequest }
     * 
     */
    public GetNoteDetailsRequest createGetNoteDetailsRequest() {
        return new GetNoteDetailsRequest();
    }

    /**
     * Create an instance of {@link AddNoteDetailsResponse }
     * 
     */
    public AddNoteDetailsResponse createAddNoteDetailsResponse() {
        return new AddNoteDetailsResponse();
    }

    /**
     * Create an instance of {@link EditNoteDetailsRequest }
     * 
     */
    public EditNoteDetailsRequest createEditNoteDetailsRequest() {
        return new EditNoteDetailsRequest();
    }

    /**
     * Create an instance of {@link GetNoteDetailsResponse }
     * 
     */
    public GetNoteDetailsResponse createGetNoteDetailsResponse() {
        return new GetNoteDetailsResponse();
    }

}
